### ISSUE TITLE
Windows executable in release should have an `.exe` suffix

### ISSUE THREAD

**Issue by lucasfcnunes** [mamba-org/micromamba-releases#24] opened 2023-12-09 08:03 UTC
As of: https://github.com/mamba-org/micromamba-releases/releases/tag/1.5.3-0
![image](https://github.com/mamba-org/micromamba-releases/assets/29926675/3e97a2c8-2248-4087-8e00-fac8e17cf80e)

Windows artifacts:
- [micromamba-win-64](https://github.com/mamba-org/micromamba-releases/releases/download/1.5.3-0/micromamba-win-64) (missing `.exe` extension)
- [micromamba-win-64.sha256](https://github.com/mamba-org/micromamba-releases/releases/download/1.5.3-0/micromamba-win-64.sha256)
- [micromamba-win-64.tar.bz2](https://github.com/mamba-org/micromamba-releases/releases/download/1.5.3-0/micromamba-win-64.tar.bz2)
- [micromamba-win-64.tar.bz2.sha256](https://github.com/mamba-org/micromamba-releases/releases/download/1.5.3-0/micromamba-win-64.tar.bz2.sha256)

**Comment by jjerphan** [comment] 2024-11-26 15:02
Closing as a duplicate of https://github.com/mamba-org/micromamba-releases/issues/61.

**Closed by jjerphan** 2024-11-26 15:02 UTC
