### ISSUE TITLE
bug with v2.0?

### ISSUE THREAD

**Issue by mikemhenry** [mamba-org/micromamba-releases#58] opened 2024-09-25 22:19 UTC
This used to work in my CI, but with the 2.0 release it breaks now:

``` 
/home/runner/.local/bin/micromamba create -y -r /home/runner/micromamba -f environment.yml -n openfe_env python=3.10 pydantic=>1 --log-level warning --rc-file /home/runner/work/_temp/setup-micromamba/.condarc
  critical libmamba Error parsing version ">1". Version contains invalid characters in >1.
```

Not sure if this is a bug or if I was abusing micromamba syntax. When I pinned the version back to `1.5.6-0` it worked again. 

Link to failed CI job: https://github.com/OpenFreeEnergy/openfe/actions/runs/11041820242/job/30672921965

**Comment by pavelzw** [comment] 2024-09-26 06:11
You should probably open an issue in the main mamba repo instead

**Comment by jjerphan** [comment] 2024-09-26 14:13
Thank you for opening this issue.

The problem you are observing has been fixed in a release candidate of 2.0.

I cannot reproduce the issue with micromamba 2.0 from conda-forge or from `setup-micromamba`.

The problem is likely due to an integration issue between `setup-micromamba` and `micromamba-releases` which picks a previous release candidate instead of 2.0.0.

We are inspecting this issue.

**Comment by breakbotz** [comment] 2024-09-26 15:57
I believe I'm running into the same (or similar) parsing issue when creating a micromamba environment via CLI (using latest version of micromamba:

`micromamba env create --yes --file environment.yml` results in:

```error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ aiohttp ~= does not exist (perhaps a typo or a missing channel);
    ├─ anthropic ~= does not exist (perhaps a typo or a missing channel);
    ├─ fluxus ~= does not exist (perhaps a typo or a missing channel);
    ├─ gamma-pytools ~= does not exist (perhaps a typo or a missing channel);
    ├─ google-generativeai ~= does not exist (perhaps a typo or a missing channel);
    ├─ graphviz ~= does not exist (perhaps a typo or a missing channel);
    ├─ groq ~= does not exist (perhaps a typo or a missing channel);
    ├─ ipywidgets ~= does not exist (perhaps a typo or a missing channel);
    ├─ jupyterlab ~= does not exist (perhaps a typo or a missing channel);
... list continues for basically every dependency listed in my environment.yaml which has not changed in months
```

**Comment by jjerphan** [comment] 2024-09-26 17:25
Hi @breakbotz,

Can you open an issue on `mamba-org/mamba` so that we can reproduce and fix the error? Thank you.

**Comment by breakbotz** [comment] 2024-09-26 17:36
> Hi @breakbotz,
> 
> Can you open an issue on `mamba-org/mamba` so that we can reproduce and fix the error? Thank you.

Created https://github.com/mamba-org/mamba/issues/3472

**Comment by SylvainCorlay** [comment] 2024-09-28 01:15
Closing as it was not related to mamba but to GitHub action picking up a pre-release rather than 2.0.

**Closed by SylvainCorlay** 2024-09-28 01:15 UTC
